package Modelo;
// Generated 19/10/2017 11:32:12 by Hibernate Tools 4.3.1



/**
 * Aulamultimedios generated by hbm2java
 */
public class Aulamultimedios  implements java.io.Serializable {


     private Integer aulaId;
     private Aula aula;
     private Boolean televisor;
     private Boolean canion;
     private Boolean computadora;
     private Boolean dvd;

    public Aulamultimedios() {
    }

	
    public Aulamultimedios(Aula aula) {
        this.aula = aula;
    }
    public Aulamultimedios(Aula aula, Boolean televisor, Boolean canion, Boolean computadora, Boolean dvd) {
       this.aula = aula;
       this.televisor = televisor;
       this.canion = canion;
       this.computadora = computadora;
       this.dvd = dvd;
    }
   
    public Integer getAulaId() {
        return this.aulaId;
    }
    
    public void setAulaId(Integer aulaId) {
        this.aulaId = aulaId;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Boolean getTelevisor() {
        return this.televisor;
    }
    
    public void setTelevisor(Boolean televisor) {
        this.televisor = televisor;
    }
    public Boolean getCanion() {
        return this.canion;
    }
    
    public void setCanion(Boolean canion) {
        this.canion = canion;
    }
    public Boolean getComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(Boolean computadora) {
        this.computadora = computadora;
    }
    public Boolean getDvd() {
        return this.dvd;
    }
    
    public void setDvd(Boolean dvd) {
        this.dvd = dvd;
    }




}


