package Modelo;
// Generated 19/10/2017 11:32:12 by Hibernate Tools 4.3.1



/**
 * Aulasra generated by hbm2java
 */
public class Aulasra  implements java.io.Serializable {


     private Integer aulaId;
     private Aula aula;

    public Aulasra() {
    }

    public Aulasra(Aula aula) {
       this.aula = aula;
    }
   
    public Integer getAulaId() {
        return this.aulaId;
    }
    
    public void setAulaId(Integer aulaId) {
        this.aulaId = aulaId;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }




}


