package Modelo;
// Generated Oct 22, 2017 3:35:48 AM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso extends Actividad implements java.io.Serializable {


     private Integer actividadId;
     private Actividad actividad;
     private String carrera;

    public Curso() {
    }

    public Curso(Actividad actividad, String carrera) {
       this.actividad = actividad;
       this.carrera = carrera;
    }
   
    @Override
    public Integer getActividadId() {
        return this.actividadId;
    }
    
    public void setActividadId(int actividadId) {
        this.actividadId = actividadId;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }




}


