package Modelo;
// Generated Oct 22, 2017 10:44:08 PM by Hibernate Tools 4.3.1



/**
 * Esporadica generated by hbm2java
 */
public class Esporadica  implements java.io.Serializable {


     private Integer reservaId;
     private Reserva reserva;

    public Esporadica() {
    }

    public Esporadica(Reserva reserva) {
       this.reserva = reserva;
    }
   
    public Integer getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(Integer reservaId) {
        this.reservaId = reservaId;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


