package Modelo;
// Generated Oct 22, 2017 3:35:48 AM by Hibernate Tools 4.3.1



/**
 * Esporadica generated by hbm2java
 */
public class Esporadica extends Reserva implements java.io.Serializable {


     private Integer reservaId;
     private Reserva reserva;

    public Esporadica() {
    }

    public Esporadica(Reserva reserva) {
       this.reserva = reserva;
    }
   
    public Integer getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(Integer reservaId) {
        this.reservaId = reservaId;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


