package Modelo;
// Generated Oct 22, 2017 2:58:22 AM by Hibernate Tools 4.3.1



/**
 * Fechalectivas generated by hbm2java
 */
public class Fechalectivas  implements java.io.Serializable {


     private FechalectivasId id;

    public Fechalectivas() {
    }

    public Fechalectivas(FechalectivasId id) {
       this.id = id;
    }
   
    public FechalectivasId getId() {
        return this.id;
    }
    
    public void setId(FechalectivasId id) {
        this.id = id;
    }




}


