package Modelo;
// Generated Oct 22, 2017 3:35:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Politicascontrasenia generated by hbm2java
 */
public class Politicascontrasenia  implements java.io.Serializable {


     private Integer politicaId;
     private Clave clave;
     private int longMin;
     private boolean signosEspeciales;
     private boolean letraMay;
     private boolean digito;
     private boolean passIgual;
     private Set claves = new HashSet(0);

    public Politicascontrasenia() {
    }

	
    public Politicascontrasenia(Clave clave, int longMin, boolean signosEspeciales, boolean letraMay, boolean digito, boolean passIgual) {
        this.clave = clave;
        this.longMin = longMin;
        this.signosEspeciales = signosEspeciales;
        this.letraMay = letraMay;
        this.digito = digito;
        this.passIgual = passIgual;
    }
    public Politicascontrasenia(Clave clave, int longMin, boolean signosEspeciales, boolean letraMay, boolean digito, boolean passIgual, Set claves) {
       this.clave = clave;
       this.longMin = longMin;
       this.signosEspeciales = signosEspeciales;
       this.letraMay = letraMay;
       this.digito = digito;
       this.passIgual = passIgual;
       this.claves = claves;
    }
   
    public Integer getPoliticaId() {
        return this.politicaId;
    }
    
    public void setPoliticaId(Integer politicaId) {
        this.politicaId = politicaId;
    }
    public Clave getClave() {
        return this.clave;
    }
    
    public void setClave(Clave clave) {
        this.clave = clave;
    }
    public int getLongMin() {
        return this.longMin;
    }
    
    public void setLongMin(int longMin) {
        this.longMin = longMin;
    }
    public boolean isSignosEspeciales() {
        return this.signosEspeciales;
    }
    
    public void setSignosEspeciales(boolean signosEspeciales) {
        this.signosEspeciales = signosEspeciales;
    }
    public boolean isLetraMay() {
        return this.letraMay;
    }
    
    public void setLetraMay(boolean letraMay) {
        this.letraMay = letraMay;
    }
    public boolean isDigito() {
        return this.digito;
    }
    
    public void setDigito(boolean digito) {
        this.digito = digito;
    }
    public boolean isPassIgual() {
        return this.passIgual;
    }
    
    public void setPassIgual(boolean passIgual) {
        this.passIgual = passIgual;
    }
    public Set getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set claves) {
        this.claves = claves;
    }




}


