package Modelo;
// Generated 19/10/2017 11:32:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer userId;
     private String nombreUsuario;
     private String nombre;
     private String apellido;
     private Set historialclaveses = new HashSet(0);
     private Bedel bedel;
     private Set claves = new HashSet(0);
     private Admin admin;

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String nombre, String apellido) {
        this.nombreUsuario = nombreUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Usuario(String nombreUsuario, String nombre, String apellido, Set historialclaveses, Bedel bedel, Set claves, Admin admin) {
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.historialclaveses = historialclaveses;
       this.bedel = bedel;
       this.claves = claves;
       this.admin = admin;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getHistorialclaveses() {
        return this.historialclaveses;
    }
    
    public void setHistorialclaveses(Set historialclaveses) {
        this.historialclaveses = historialclaveses;
    }
    public Bedel getBedel() {
        return this.bedel;
    }
    
    public void setBedel(Bedel bedel) {
        this.bedel = bedel;
    }
    public Set getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set claves) {
        this.claves = claves;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }




}


